
/*
        <SEQUENCE>
            SEQUENCE는 오라클에서 제공하는 객체로 순차적으로 정수 값을 자동으로 생성한다.
*/
-- 1. SEQUENCE 생성
-- TB_MEMBER 테이블의 PK 값을 생성할 시퀀스 생성

CREATE SEQUENCE SEQ_MNO
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE
;

-- 현재 계정이 가지고 있는 시퀀스들에 대한 정보를 조회하는 뷰 테이블이다.
SELECT * FROM USER_SEQUENCES;

-- 2. SEQUENCE 사용
-- NEXTVAL를 한 번이라도 수행하지 않은 상태에서 CURRVAL를 가져올 수 없다.
-- CURRVAL는 마지막으로 수행된 NEXTVAL 값을 저장해서 보여주는 값이다.



SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 300
SELECT SEQ_MNO.CURRVAL FROM DUAL;
SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 305
SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 310
SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 에러 발생 : MAX VALUE 값을 초과해서
SELECT SEQ_MNO.CURRVAL FROM DUAL; -- 310

-- 3. SEQUENCE 수정
ALTER  SEQUENCE SEQ_MNO
--START WITH 200;   -- 시퀀스 시작 번호는 변경할 수 없다.
INCREMENT BY 10
MAXVALUE 400;

SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 320
SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 330
SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 340
SELECT SEQ_MNO.NEXTVAL FROM DUAL; -- 350
SELECT SEQ_MNO.CURRVAL FROM DUAL; -- 350

-- 4. SEQUENCE 예시
-- 매번 새로운 회원 번호를 생성하는 SEQUENCE를 사용해서 INSERT 작성
INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME)
VALUES (SEQ_MNO.NEXTVAL, 'ISMOON', '1234', '홍길동');

INSERT INTO TB_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME)
VALUES (SEQ_MNO.NEXTVAL, 'MOON', '5678', '문문문');

-- 5. SEQUENCE 삭제
DROP SEQUENCE SEQ_MNO;






























