
/*
        <ALTER>
            오라클 데이터 베이스 객체(테이블, 인덱스, 뷰 등)를 수정하는 구문이다.
            
*/
-- 실습에 사용할 테이블 생성
CREATE TABLE DEPT_COPY
AS SELECT *
    FROM DEPARTMENT;



/*
        1. 컬럼 추가 / 수정 / 삭제 / 이름 변경
            1) 컬럼 추가
                ALTER TABLE 테이블명 ADD 컬럼명 데이터타입 [DEFAULT 기본값];
*/
-- DEPT_COPY 테이블에 CNAME 칼럼을 추가
ALTER TABLE DEPT_COPY ADD CNAME VARCHAR2(20);

-- DEPT_COPY 테이블에 LNAME 컬럼을 추가 (기본값 : 대한민국)
ALTER TABLE DEPT_COPY ADD LNAME VARCHAR2(20) DEFAULT '대한민국';

SELECT * FROM DEPT_COPY;

/*
          2) 컬럼 수정
            데이터 타입 변경
                ALTER TABLE 테이블명 MODIFY 컬럼명 변경할 데이터 타입;
            기본값 변경
                ALTER TABLE 테이블명 MODIFY 컬럼명 DEFALUT 변경할 기본값;
*/
-- DEPT_COPY 테이블에 DEPT_ID 컬럼의 데이터 타입을 CHAR(3)로 변경
ALTER TABLE DEPT_COPY MODIFY DEPT_ID CHAR(3);
-- 변경하려는 자료형의 크기보다 이미 큰 값이 존재하면 에러 발생
-- ALTER TABLE DEPT_COPY MODIFY DEPT_ID CHAR(2);
-- ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE VARCHAR(10);

-- DEPT_COPY 테이블에 CNAME 컬럼의 데이터 타입을 NUMBER로 변경


ALTER TABLE DEPT_COPY MODIFY CNAME NUMBER;
-- ALTER TABLE DEPT_COPY MODIFY LNAME NUMBER; -- 에러 발생

-- DEPT_COPY 테이블에 LNAME 칼럼의 기본값을 미국으로 변경
ALTER TABLE DEPT_COPY MODIFY LNAME DEFAULT '미국';
ALTER TABLE DEPT_COPY MODIFY LNAME DEFAULT NULL; -- DEFALUT 삭제

SELECT * FROM DEPT_COPY;

-- DEPT_COPY 테이블에 
-- DEPT_TITLE 컬럼의 데이터 타입을 VARCHAR2(40)로 변경
-- LOCATION_ID 컬럼의 데이터 타입을 VARCHAR2(2)로
-- LNAME 컬럼의 기본값을 한국으로 변경하기
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE VARCHAR2(40);
ALTER TABLE DEPT_COPY MODIFY LOCATION_ID VARCHAR2(2);
ALTER TABLE DEPT_COPY MODIFY LNAME DEFAULT '한국';

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE VARCHAR2(40)
MODIFY LOCATION_ID VARCHAR2(2)
MODIFY LNAME DEFAULT '한국'
;


/*
            2) 컬럼 삭제
                ALTER TABLE 테이블명 DROP COLUMN  컬럼명;
*/
-- DEPT_COPY 테이블에서 DEPT_ID 컬럼 삭제
ALTER TABLE DEPT_COPY
DROP COLUMN DEPT_ID;

SELECT * FROM DEPT_COPY;
ROLLBACK;       -- DDL 구문은 ROLLBACK으로 복구 불가능

-- 테이블에 최소 한 개의 컬럼은 존재해야한다.
ALTER TABLE DEPT_COPY DROP COLUMN DEPT_TITLE;
ALTER TABLE DEPT_COPY DROP COLUMN LOCATION_ID;
ALTER TABLE DEPT_COPY DROP COLUMN CNAME;
ALTER TABLE DEPT_COPY DROP COLUMN LANME; -- 에러 발생
;
-- 참조되고 있는 컬럼이 있다면 삭제가 불가능하다.
ALTER TABLE MEMBER_GRADE DROP COLUMN GRADE_CODE;

-- 아래와 같이 옵션을 지정하면 참조되고 있는 칼럼도 삭제가 가능하다.
-- 단, 참조하고 있는 컬럼의 제약조건도 삭제된다.
ALTER TABLE MEMBER_GRADE DROP COLUMN GRADE_CODE CASCADE CONSTRAINTS;

/*
            4) 컬럼명 변경
                ALTER TABLE 테이블명 RENAME COLUMN 기존컬럼명 TO 변경할 컬럼명;
*/
-- DEPT_COPY 테이블의 LNAME 컬럼명을 LOCATION_NAME 으로 변경
ALTER TABLE DEPT_COPY 
RENAME COLUMN LNAME TO LOCATION_NAME;

SELECT * FROM DEPT_COPY;
DROP TABLE DEPT_COPY;

/*
        2. 제약조건 추가 / 삭제 / 이름 변경
            1) 제약조건 추가
                -- 제약조건 추가 (PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK)
                    ALTER TABLE 테이블명 ADD [CONSTRAINT 제약조건명] 제약조건(컬럼명);  

                -- NOT NULL 제약조건 추가
                    ALTER TABLE 테이블명 MODIFY 컬럼명 [CONSTRAINT 제약조건명] NOT NULL;
*/
-- 실습에 사용할 테이블 생성
CREATE TABLE DEPT_COPY
AS SELECT *
    FROM DEPARTMENT;

-- DEPT_COPY 테이블에 DEPT_ID 컬럼에 PK 제약조건 추가
ALTER TABLE DEPT_COPY
ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPT_ID);

-- DEPT_COPY 테이블의 DEPT_TITLE 컬럼에 UNIQUE 제약조건 추가
ALTER TABLE DEPT_COPY
ADD CONSTRAINT DEPT_TITLE_UQ UNIQUE (DEPT_TITLE);

-- DEPT_COPY 테이블의 DEPT_TITLE 컬럼에 NOT NULL 제약조건 추가
ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE NOT NULL;

DROP TABLE DEPT_COPY;
SELECT * FROM DEPT_COPY;
------------------------------------------------------------------------------------------------------------------------------------

-- EMPLOYEE 테이블에 DEPT_CODE, JOB_CODE 컬럼에 
-- FOREIGN KEY 제약조건을 추가
ALTER TABLE EMPLOYEE
ADD CONSTRAINT DEPT_CODE_FK 
FOREIGN KEY (DEPT_CODE)
REFERENCES DEPARTMENT(DEPT_ID);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT JOB_CODE_FK 
FOREIGN KEY (JOB_CODE)
REFERENCES JOB(JOB_CODE);

-- MEMBER_GRADE 테이블 생성 후 PK, NOT NULL 제약조건을 추가
CREATE TABLE MEMBER_GRADE(
    GRADE_CODE NUMBER,
    GRADE_NAME VARCHAR2(20)
);

ALTER TABLE MEMBER_GRADE
ADD CONSTRAINT GRADE_CODE_PK
PRIMARY KEY (GRADE_CODE);

ALTER TABLE MEMBER_GRADE
MODIFY GRADE_NAME CONSTRAINT GRADE_NAME_NN NOT NULL
;

INSERT INTO MEMBER_GRADE VALUES (10, '일반회원');
INSERT INTO MEMBER_GRADE VALUES (20, '우수회원');
INSERT INTO MEMBER_GRADE VALUES (10, NULL);

DROP TABLE MEMBER_GRADE;

-- MEMBER 테이블 생성 후 제약 조건을 추가

CREATE TABLE MEMBER (
    NO NUMBER,
    ID VARCHAR2(20),
    PASSWORD VARCHAR2(20),
    NAME VARCHAR2(15),
    GENDER CHAR(3),
    AGE NUMBER,
    GRADE_ID NUMBER,
    ENROLL_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_NO_PK1 
PRIMARY KEY (NO);

ALTER TABLE MEMBER
MODIFY ID CONSTRAINT MEMBER_ID_NN NOT NULL;

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_ID_UQ1 UNIQUE (ID);

ALTER TABLE MEMBER
MODIFY PASSWORD NOT NULL;

ALTER TABLE MEMBER
MODIFY NAME NOT NULL;

ALTER TABLE MEMBER
MODIFY PASSWORD NOT NULL;

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_GENDER_CK 
CHECK (GENDER IN('남','여')) ;

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_AGE_CK CHECK (AGE>0);

ALTER TABLE MEMBER
ADD  CONSTRAINT MEMBER_GRADE_ID_FK
FOREIGN KEY (GRADE_ID) REFERENCES MEMBER_GRADE;
--FOREIGN KEY (GRADE_ID) REFERENCES MEMBER_GRADE ON DELETE CASCADE;

INSERT INTO MEMBER VALUES(1, 'USER1', '1234', '홍길동', '남', '22', 10, DEFAULT);
INSERT INTO MEMBER VALUES(2, 'USER2', '1234', '성춘향', '여', '22', NULL, DEFAULT);
INSERT INTO MEMBER VALUES(2, 'USER2', '1234', '성춘향', '여', '22', 50, DEFAULT);

SELECT * FROM MEMBER;

/*
            2) 제약 조건 삭제
                NOT NULL
                    ALTER TABLE 테이블명 MODIFY 컬럼명 NULL;
                
                나머지
                    ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
*/

-- DEPT_COPY 테이블의 DEPT_ID_PK 제약조건 삭제
ALTER TABLE DEPT_COPY
DROP CONSTRAINT DEPT_ID_PK;

--  DEPT_COPY 테이블의 DEPT_TITLE 컬럼의 UQ, NN 제약조건 삭제
ALTER TABLE DEPT_COPY
DROP CONSTRAINT DEPT_TITLE_UQ;

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE NULL;

/*
            3) 제약조건명 변경
                ALTER TABLE 테이블명 RENAME CONSTRAINT 기존 제약조건명 TO 변경할제약조건명;
*/

--  DEPT_COPY 테이블의 SYS_C008590 제약조건명을 DEPT_ID_NN로 변경
ALTER TABLE DEPT_COPY
RENAME CONSTRAINT SYS_C008590 TO DEPT_ID_NN;

--  DEPT_COPY 테이블의 SYS_C008591 제약조건명을 LOCATION_ID_NN로 변경
ALTER TABLE DEPT_COPY
RENAME CONSTRAINT SYS_C008591 TO LOCATION_ID_NN;

/*
        3. 테이블명 변경
            ALTER TABLE 테이블명 RENAME TO 변경할 테이블명;
            RENAME 기존 테이블명 TO 변경할 테이블명;
*/
--  DEPT_COPY 테이블의 이름을 DEPT_TEST로 변경
ALTER TABLE DEPT_COPY RENAME TO DEPT_TEST;
--  DEPT_TEST 테이블의 이름을 DEPT_COPY로 변경
RENAME DEPT_TEST TO DEPT_COPY;

/*
        <DROP>
            오라클에서 제공하는 객체를 삭제하는 구문이다.
*/
-- DEPT_COPY 테이블 삭제
DROP TABLE DEPT_COPY;

-- MEMBER_GRADE 테이블 삭제
-- 참조되고 있는 부모 테이블은 함부로 삭제가 되지 않는다.
DROP TABLE MEMBER_GRADE;

-- 만약에 부모 테이블을 삭제하고자 한다면
-- 1) 자식 테이블 먼저 삭제한 후 부모 테이블을 삭제한다
DROP TABLE MEMBER;
DROP TABLE MEMBER_GRADE;

-- 2) 아래와 같이 옵션을 지정하면 부모 테이블을 삭제할수 있다.
--      단, 참조하고 있는 자식 테이블의 제약조건도 삭제된다.
DROP TABLE MEMBER_GRADE CASCADE CONSTRAINTS;